[package]
name = "csds426-clock-project"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
csv = "1.4.0"
httpdate = "1.0.3"
ureq = "3.1.4"
spin_sleep = "1.3.3"
chrono = "0.4.43"
